const TIMES = ["past", "present", "future"]
const ASPECTS = ["simple", "cont", "perf", "perfcont"]

const TIME_INFO = {
  past: {name: "Past", look: "look from a moment then", ru: "смотрим из момента в прошлом"},
  present: {name: "Present", look: "look from now", ru: "смотрим из «сейчас»"},
  future: {name: "Future", look: "look from a moment later", ru: "смотрим из момента в будущем"},
}

const ASPECT_INFO = {
  simple: {name: "Simple", shape: "whole fact", ru: "факт целиком"},
  cont: {name: "Continuous", shape: "in progress at it", ru: "в процессе в этот момент"},
  perf: {name: "Perfect", shape: "done before it", ru: "сделано к этому моменту"},
  perfcont: {name: "Perfect Continuous", shape: "going on up to it", ru: "длится до этого момента"},
}

const TENSES = {
  "present.simple": {formula: "V / V+s", gloss: "Бывает регулярно или это факт вообще.", markers: "usually, often, every day, always"},
  "present.cont": {formula: "am / is / are + V-ing", gloss: "Происходит прямо сейчас, в процессе.", markers: "now, at the moment, Look!, Listen!"},
  "present.perf": {formula: "have / has + V3", gloss: "Уже случилось к настоящему моменту; важен результат сейчас.", markers: "already, just, yet, ever, never, since, for"},
  "present.perfcont": {formula: "have / has been + V-ing", gloss: "Началось раньше и длится до сих пор — важна длительность.", markers: "for two hours, since morning, all day, how long"},
  "past.simple": {formula: "V2", gloss: "Случилось в прошлом и закончилось; с «сейчас» не связано.", markers: "yesterday, last year, ago, in 2019, when"},
  "past.cont": {formula: "was / were + V-ing", gloss: "В определённый момент в прошлом было в процессе.", markers: "at 5 pm yesterday, when…, while…"},
  "past.perf": {formula: "had + V3", gloss: "Случилось ещё раньше другого момента в прошлом.", markers: "by then, before, already, by the time"},
  "past.perfcont": {formula: "had been + V-ing", gloss: "Длилось какое-то время до момента в прошлом.", markers: "for an hour, since, before…, by the time"},
  "future.simple": {formula: "will + V", gloss: "Случится в будущем: решение, обещание, прогноз.", markers: "tomorrow, next week, I think, I'm sure"},
  "future.cont": {formula: "will be + V-ing", gloss: "В определённый момент в будущем будет в процессе.", markers: "at 9 tomorrow, this time next week"},
  "future.perf": {formula: "will have + V3", gloss: "Будет сделано к моменту в будущем.", markers: "by Friday, by the time, by then"},
  "future.perfcont": {formula: "will have been + V-ing", gloss: "К моменту в будущем будет длиться уже какое-то время.", markers: "by June … for a year"},
}

const tenseName = (key) => {
  const [t, a] = key.split(".")
  return `${TIME_INFO[t].name} ${ASPECT_INFO[a].name}`
}

const VERBS = {
  get: ["get", "gets", "got", "got", "getting"],
  sleep: ["sleep", "sleeps", "slept", "slept", "sleeping"],
  lose: ["lose", "loses", "lost", "lost", "losing"],
  rain: ["rain", "rains", "rained", "rained", "raining"],
  visit: ["visit", "visits", "visited", "visited", "visiting"],
  cook: ["cook", "cooks", "cooked", "cooked", "cooking"],
  leave: ["leave", "leaves", "left", "left", "leaving"],
  run: ["run", "runs", "ran", "run", "running"],
  pass: ["pass", "passes", "passed", "passed", "passing"],
  drive: ["drive", "drives", "drove", "driven", "driving"],
  finish: ["finish", "finishes", "finished", "finished", "finishing"],
  study: ["study", "studies", "studied", "studied", "studying"],
  break: ["break", "breaks", "broke", "broken", "breaking"],
  see: ["see", "sees", "saw", "seen", "seeing"],
  start: ["start", "starts", "started", "started", "starting"],
  come: ["come", "comes", "came", "come", "coming"],
  go: ["go", "goes", "went", "gone", "going"],
  work: ["work", "works", "worked", "worked", "working"],
  eat: ["eat", "eats", "ate", "eaten", "eating"],
  watch: ["watch", "watches", "watched", "watched", "watching"],
  live: ["live", "lives", "lived", "lived", "living"],
  sit: ["sit", "sits", "sat", "sat", "sitting"],
  wait: ["wait", "waits", "waited", "waited", "waiting"],
  drink: ["drink", "drinks", "drank", "drunk", "drinking"],
  fly: ["fly", "flies", "flew", "flown", "flying"],
}

const ITEMS = [
  {
    id: "get-up",
    tense: "present.simple",
    subj: "he",
    verb: "get",
    en: "She usually ___ up at six.",
    ru: "Она обычно встаёт в шесть.",
    shape: "habit",
    rLabel: "now",
    mark: ["usually"],
    why: "Привычка, повторяется регулярно — Present Simple. «Обычно» не про «сейчас», а про «вообще».",
  },
  {
    id: "baby",
    tense: "present.cont",
    subj: "he",
    verb: "sleep",
    en: "Be quiet! The baby ___.",
    ru: "Тише! Ребёнок спит.",
    rLabel: "now",
    mark: ["Be quiet!"],
    why: "Прямо сейчас, в процессе — Present Continuous. По-русски тоже «спит», поэтому легко перепутать с Present Simple (the baby sleeps = ребёнок вообще спит, например, много).",
  },
  {
    id: "keys",
    tense: "present.perf",
    subj: "I",
    verb: "lose",
    en: "I can't open the door — I ___ my keys.",
    ru: "Не могу открыть дверь — я потерял ключи.",
    rLabel: "now",
    mark: ["can't open"],
    why: "Потерял в прошлом, но важен результат сейчас: ключей нет, дверь не открыть. По-русски прошедшее, по-английски Present Perfect.",
  },
  {
    id: "rain",
    tense: "present.perfcont",
    subj: "he",
    verb: "rain",
    en: "It ___ since morning, and the streets are flooded.",
    ru: "Дождь идёт с самого утра, улицы затопило.",
    rLabel: "now",
    dur: "since morning",
    mark: ["since morning"],
    why: "Началось в прошлом (с утра) и идёт до сих пор — Present Perfect Continuous. По-русски тут настоящее время «идёт», в этом ловушка.",
  },
  {
    id: "rome",
    tense: "past.simple",
    subj: "we",
    verb: "visit",
    en: "We ___ Rome last summer.",
    ru: "Прошлым летом мы побывали в Риме.",
    rLabel: "last summer",
    mark: ["last summer"],
    why: "Конкретный момент в прошлом (last summer), с «сейчас» не связано — Past Simple. С last summer Present Perfect не сочетается.",
  },
  {
    id: "dinner",
    tense: "past.cont",
    subj: "he",
    verb: "cook",
    en: "When I came home, my wife ___ dinner.",
    ru: "Когда я пришёл домой, жена готовила ужин.",
    rLabel: "I came",
    mark: ["When I came home"],
    why: "В момент «когда я пришёл» готовка уже шла — Past Continuous. С cooked получилось бы, что она начала готовить после твоего прихода.",
  },
  {
    id: "train",
    tense: "past.perf",
    subj: "he",
    verb: "leave",
    en: "When we got to the station, the train ___.",
    ru: "Когда мы добрались до вокзала, поезд уже ушёл.",
    rLabel: "we got there",
    mark: ["When we got to the station"],
    why: "Поезд ушёл ещё раньше момента в прошлом (мы добрались) — Past Perfect. С left вышло бы, что он ушёл в момент нашего прихода.",
  },
  {
    id: "breath",
    tense: "past.perfcont",
    subj: "he",
    verb: "run",
    en: "She was out of breath because she ___.",
    ru: "Она запыхалась, потому что бежала.",
    rLabel: "out of breath",
    dur: "a while",
    mark: ["was out of breath"],
    why: "Бег длился какое-то время до момента в прошлом, и видно последствие — Past Perfect Continuous.",
  },
  {
    id: "exam",
    tense: "future.simple",
    subj: "you",
    verb: "pass",
    en: "Don't worry, I'm sure you ___ the exam.",
    ru: "Не волнуйся, уверен, ты сдашь экзамен.",
    rLabel: "the exam",
    mark: ["I'm sure"],
    why: "Предсказание о будущем — Future Simple (will + V). I'm sure, I think — частые маркеры.",
  },
  {
    id: "drive",
    tense: "future.cont",
    subj: "I",
    verb: "drive",
    en: "Don't call me at nine — I ___ to work.",
    ru: "Не звони мне в девять — я буду ехать на работу.",
    rLabel: "at nine",
    mark: ["at nine"],
    why: "В момент в будущем (в девять) действие будет в процессе — Future Continuous. Тот же таймлайн, что у Past Continuous, только момент в будущем.",
  },
  {
    id: "report",
    tense: "future.perf",
    subj: "I",
    verb: "finish",
    en: "By Friday I ___ the report.",
    ru: "К пятнице я закончу отчёт.",
    rLabel: "by Friday",
    mark: ["By Friday"],
    why: "Будет готово к моменту в будущем — Future Perfect. Главный маркер — by + время.",
  },
  {
    id: "year",
    tense: "future.perfcont",
    subj: "I",
    verb: "study",
    en: "By June I ___ English for a year.",
    ru: "В июне будет год, как я учу английский.",
    rLabel: "by June",
    dur: "a year",
    mark: ["By June", "for a year"],
    why: "К моменту в будущем будет длиться уже год — Future Perfect Continuous. Редкое время, но таймлайн как у Present Perfect Continuous, просто сдвинут в будущее.",
  },
  {
    id: "window",
    tense: "present.perf",
    subj: "he",
    verb: "break",
    en: "Look! Someone ___ the window.",
    ru: "Смотри! Кто-то разбил окно.",
    rLabel: "now",
    mark: ["Look!"],
    why: "Разбили в прошлом, а смотрим на результат сейчас — Present Perfect.",
  },
  {
    id: "film",
    tense: "past.simple",
    subj: "I",
    verb: "see",
    en: "I ___ this film yesterday.",
    ru: "Я видел этот фильм вчера.",
    rLabel: "yesterday",
    mark: ["yesterday"],
    why: "yesterday — конкретный момент в прошлом, поэтому Past Simple. «I have seen it yesterday» — типичная ошибка.",
  },
]

const STORIES = [
  {
    id: "evening",
    title: "Yesterday evening",
    now: 930,
    refs: [{x: 520, label: "I came home"}],
    ru: "Вчера я пришёл домой поздно. Жена готовила ужин, а дети к тому времени уже легли спать. Она работала весь день, так что очень устала. Потом мы поели и посмотрели фильм.",
    parts: [
      "Yesterday I ",
      {tense: "past.simple", subj: "I", verb: "come", rx: 520},
      " home late. My wife ",
      {tense: "past.cont", subj: "he", verb: "cook", rx: 520},
      " dinner, and by then the kids ",
      {tense: "past.perf", subj: "they", verb: "go", rx: 520},
      " to bed. She ",
      {tense: "past.perfcont", subj: "he", verb: "work", rx: 520, dur: "all day", also: ["past.perf"]},
      " all day, so she was really tired. Then we ",
      {tense: "past.simple", subj: "we", verb: "eat", rx: 680},
      " and ",
      {tense: "past.simple", subj: "we", verb: "watch", rx: 790},
      " a film.",
    ],
  },
  {
    id: "cafe",
    title: "In a café",
    now: 400,
    refs: [
      {x: 610, label: "she comes"},
      {x: 850, label: "this time tomorrow"},
    ],
    ru: "Я живу в Берлине. Сейчас сижу в кафе. Жду Анну уже сорок минут и выпил уже две чашки кофе. К тому времени, как она придёт, я дочитаю книгу! А завтра в это время мы будем лететь в Рим.",
    parts: [
      "I ",
      {tense: "present.simple", subj: "I", verb: "live", rx: 400, shape: "state"},
      " in Berlin. Right now I ",
      {tense: "present.cont", subj: "I", verb: "sit", rx: 400},
      " in a café. I ",
      {tense: "present.perfcont", subj: "I", verb: "wait", rx: 400, dur: "40 min"},
      " for Anna for forty minutes, and I ",
      {tense: "present.perf", subj: "I", verb: "drink", rx: 400, shape: "points"},
      " two coffees already. By the time she comes, I ",
      {tense: "future.perf", subj: "I", verb: "finish", rx: 610},
      " my book! This time tomorrow we ",
      {tense: "future.cont", subj: "we", verb: "fly", rx: 850},
      " to Rome.",
    ],
  },
]

const PAIRS = [
  {
    id: "paris",
    a: {en: "I *lived* in Paris for five years.", tense: "past.simple", shape: "span", dur: "5 years", ru: "Я жил в Париже пять лет — теперь уже не живу."},
    b: {en: "I *have lived* in Paris for five years.", tense: "present.perf", shape: "span", dur: "5 years", ru: "Я живу в Париже уже пять лет — и сейчас тоже."},
  },
  {
    id: "cooked",
    a: {en: "When she came, I *cooked* dinner.", tense: "past.simple", shape: "after", rLabel: "she came", ru: "Она пришла — и тогда я приготовил ужин."},
    b: {en: "When she came, I *was cooking* dinner.", tense: "past.cont", rLabel: "she came", ru: "Когда она пришла, я как раз готовил ужин."},
  },
  {
    id: "smoke",
    a: {en: "He *smokes*.", tense: "present.simple", shape: "habit", ru: "Он курит — он курильщик."},
    b: {en: "He *is smoking*.", tense: "present.cont", ru: "Он сейчас курит — вон, на балконе."},
  },
  {
    id: "book",
    a: {en: "I *have read* your book.", tense: "present.perf", ru: "Я прочитал твою книгу — могу вернуть."},
    b: {en: "I *have been reading* your book.", tense: "present.perfcont", dur: "all morning", ru: "Я читал твою книгу всё утро — ещё не дочитал."},
  },
  {
    id: "station",
    a: {en: "When I arrived, the train *left*.", tense: "past.simple", shape: "after", rLabel: "I arrived", ru: "Я приехал — и поезд тут же отправился."},
    b: {en: "When I arrived, the train *had left*.", tense: "past.perf", rLabel: "I arrived", ru: "Когда я приехал, поезд уже ушёл."},
  },
  {
    id: "nine",
    a: {en: "At nine I *will write* the report.", tense: "future.simple", rLabel: "at nine", ru: "В девять я сяду писать отчёт."},
    b: {en: "At nine I *will be writing* the report.", tense: "future.cont", rLabel: "at nine", ru: "В девять я буду в процессе — писать отчёт."},
  },
]
